language: python
python:
 - "2.7"

install:
 - wget -q -O - http://www.bunkus.org/gpg-pub-moritzbunkus.txt | sudo apt-key add -
 - echo "deb http://www.bunkus.org/ubuntu/precise/ ./" | sudo tee -a /etc/apt/sources.list
 - echo "deb-src http://www.bunkus.org/ubuntu/precise/ ./" | sudo tee -a /etc/apt/sources.list
 - sudo apt-get update -qq 
 - sudo apt-get install -y -qq imagemagick mkvtoolnix ffmpeg libav-tools optipng jpegoptim python-nose mkvtoolnix mediainfo python-pip
 - pip install lxml
before_script: cp core/tests/tests.cfg configuration/pyscrape.cfg
script: python -m unittest discover core/tests/ --pattern=*.py --verbose
notifications:
  email: false
